---
- set_fact:
    label_selector_value: "galera_cluster={{ galera_cluster_name }},app={{ galera_app_name }}"

- block:
  - name: lookup k8s secrets
    set_fact:
      secrets_lookup: "{{ q('k8s', api_version='v1', kind='Secret', namespace=namespace, label_selector=label_selector_value) }}"
  rescue:
  - name: set secrets if they don't exist
    set_fact:
      secrets_lookup: []

- block:
  - name: lookup k8s configmap
    set_fact:
      configmap_lookup: "{{ q('k8s', api_version='v1', kind='ConfigMap', namespace=namespace, resource_name=galera_configmap_name) }}"
  rescue:
  - name: set configmap_lookup to default on failure to find GVK
    set_fact:
      configmap_lookup: []

- block:
  - name: lookup k8s service
    set_fact:
      services_lookup: "{{ q('k8s', api_version='v1', kind='Service', namespace=namespace, label_selector=label_selector_value) }}"
  rescue:
  - name: set services_lookup to default on failure to find GVK
    set_fact:
      services_lookup: []

- block:
  - name: lookup pods
    set_fact:
      pods_lookup: "{{ q('k8s', api_version='v1', kind='Pod', namespace=namespace, label_selector=label_selector_value) }}"
  rescue:
  - name: set pods_lookup to default on failure to find GVK
    set_fact:
      pods_lookup: []

- name: lookup k8s GaleraService
  set_fact:
    galera_service_lookup: "{{ q('k8s', api_version='galera.database.coreos.com/v1alpha1', kind='GaleraService', namespace=namespace, resource_name=galera_cluster_name) }}"

- debug: var=configmap_lookup
- debug: var=services_lookup
- debug: var=galera_service_lookup
- debug: var=pods_lookup
