apiVersion: v1
kind: Service
metadata:
  name: example-custom-service
  namespace: default
  labels:
    app: vault
    vault_cluster: example
spec:
  type: ClusterIP
  selector:
    app: vault
    vault_cluster: example
  ports:
  - name: vault-client
    port: 8300
    protocol: TCP
    targetPort: 8300
  - name: vault-cluster
    port: 8201
    protocol: TCP
    targetPort: 8201
  - name: prometheus
    port: 9102
    protocol: TCP
    targetPort: 9102
