apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vault-ansible-operator
  template:
    metadata:
      labels:
        name: vault-ansible-operator
    spec:
      containers:
        - name: vault-ansible-operator
          image: quay.io/jkig/vault-ansible-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
