[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[override]]
  # TODO: use version instead of branch
  name = "github.com/coreos/etcd-operator"
  branch = "master"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version ="v0.0.5" 
