apiVersion: v1
kind: Pod
metadata:
  name: memcached-operator-test
spec:
  restartPolicy: Never
  containers:
  - name: memcached-operator-test
    image: quay.io/example/memcached-operator:v0.0.1
    imagePullPolicy: Always
    command: ["/go-test.sh"]
    env:
      - name: TEST_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
