---
- name: create a configmap
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ vault_configmap_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "vault.hcl":
          telemetry {
            statsd_address = "localhost:{{ vault_statsd_port_num }}"
          }

          listener "tcp" {
            address         = "0.0.0.0:{{ vault_client_port_num }}"
            cluster_address = "0.0.0.0:{{ vault_cluster_port_num }}"
            tls_cert_file   = "{{ vault_tls_asset_dir }}/{{ server_tls_cert_name }}"
            tls_key_file    = "{{ vault_tls_asset_dir }}/{{ server_tls_key_name }}"
          }

          storage "etcd" {
            address       = "https://{{ vault_cluster_name }}-etcd-client:2379"
            etcd_api      = "v3"
            ha_enabled    = "true"
            tls_ca_file   = "{{ vault_tls_asset_dir }}/{{ client_tls_ca_crt_name }}"
            tls_cert_file = "{{ vault_tls_asset_dir }}/{{ client_tls_cert_name }}"
            tls_key_file  = "{{ vault_tls_asset_dir }}/{{ client_tls_key_name }}"
            sync          = "false"
          }
