---
- name: Create vault service
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ vault_cluster_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      spec:
        type: ClusterIP
        selector:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
        ports:
        - name: "{{ vault_client_port_name }}"
          port: "{{ vault_client_port_num }}"
          protocol: TCP
          targetPort: "{{ vault_client_port_num }}"
        - name: "{{ vault_cluster_port_name }}"
          port: "{{ vault_cluster_port_num }}"
          protocol: TCP
          targetPort: "{{ vault_cluster_port_num }}"
        - name: "{{ vault_prometheus_port_name }}"
          port: "{{ vault_prometheus_port_num }}"
          protocol: TCP
          targetPort: "{{ vault_prometheus_port_num }}"
