---
# tasks file for Bitd
- name: start bitd
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-bitd'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          matchLabels:
            app: bitd
        template:
          metadata:
            labels:
              app: bitd
          spec:
            containers:
            - name: bitd
              image: "docker.io/dymurray/bitcoin-sv-bitd"
              ports:
                - containerPort: 8332
