---
- name: set new members empty list
  set_fact:
    etcd_new_members: []

- name: generate member names if cluster is new
  when: etcd_cluster_phase == "new"
  set_fact:
    etcd_new_members: "{{ etcd_new_members + [etcd_cluster_name + '-' + 9999999|random|hash('md5')|regex_search('^.{0,10}')] }}"
  with_sequence: start={{etcd_members|length}} end={{size - 1}}

- name: generate member names if cluster is expanding
  set_fact:
    etcd_new_members: "{{ [etcd_cluster_name + '-' + 9999999|random|hash('md5')|regex_search('^.{0,10}')] }}"
  when: etcd_cluster_phase == "existing"