- hosts: localhost
  gather_facts: no
  tasks:
  - set_fact:
      wsrep_status: "{{ q('mysql_status', 'localhost', user='root')[0] }}"
  - debug:
      var: wsrep_status
  - assert:
      that:
      - "'wsrep_connected' in wsrep_status"
      - "wsresp_status.wsrep_connected|lower == 'on'"
