- set_fact:
    removed_pod: "{{pods_lookup[remove_pod_idx|int-1]}}"

- debug:
    msg: "REMOVING NODE {{removed_pod.metadata.name}}"

- name: "REMOVING POD FOR GALERA NODE {{removed_pod.metadata.name}}"
  k8s:
    state: absent
    definition:
      kind: Pod
      apiVersion: v1
      metadata:
        name: "{{ removed_pod.metadata.name }}"
        namespace: "{{ namespace }}"

- name: "REMOVING PVC FOR GALERA NODE {{removed_pod.metadata.name}}"
  k8s:
    state: absent
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: "{{ removed_pod.metadata.name + '-mysql-data' }}"
        namespace: "{{ namespace }}"

- name: "REMOVING CONFIGMAP FOR GALERA NODE {{removed_pod.metadata.name}}"
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ galera_configmap_name }}-{{removed_pod.metadata.name}}"
        namespace: "{{ namespace }}"

- name: "REMOVE SERVICE FOR GALERA NODE {{removed_pod.metadata.name}}"
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ removed_pod.metadata.name }}-service"
        namespace: "{{ namespace }}"

