---
- name: Read Cert Files into variables
  set_fact:
    etcd_ca_crt_value: "{{ lookup('file', '{{ etcd_ca_crt_filename }}') | b64encode }}"
    etcd_peer_crt_value: "{{ lookup('file', '{{ etcd_peer_crt_filename }}') | b64encode }}"
    etcd_peer_key_value: "{{ lookup('file', '{{ etcd_peer_key_filename }}') | b64encode }}"
    etcd_client_crt_value: "{{ lookup('file', '{{ etcd_client_crt_filename }}') | b64encode }}"
    etcd_client_key_value: "{{ lookup('file', '{{ etcd_client_key_filename }}') | b64encode }}"
    etcd_server_crt_value: "{{ lookup('file', '{{ etcd_server_crt_filename }}') | b64encode }}"
    etcd_server_key_value: "{{ lookup('file', '{{ etcd_server_key_filename }}') | b64encode }}"

- name: Create Etcd Peer TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_peer_secret_name }}"
        namespace: "{{ etcd_namespace }}"
        labels:
          app: "{{ etcd_app_label }}"
          etcd_cluster: "{{ etcd_cluster_name }}"
      data:
        "peer.key": "{{ etcd_peer_key_value }}"
        "peer.crt": "{{ etcd_peer_crt_value }}"
        "peer-ca.crt": "{{ etcd_ca_crt_value }}"

- name: Create Etcd Client TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_client_secret_name }}"
        namespace: "{{ etcd_namespace }}"
        labels:
          app: "{{ etcd_app_label }}"
          etcd_cluster: "{{ etcd_cluster_name }}"
      data:
        "etcd-client.key": "{{ etcd_client_key_value }}"
        "etcd-client.crt": "{{ etcd_client_crt_value }}"
        "etcd-client-ca.crt": "{{ etcd_ca_crt_value }}"

- name: Create Etcd Server TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_server_secret_name }}"
        namespace: "{{ etcd_namespace }}"
        labels:
        app: "{{ etcd_app_label }}"
        etcd_cluster: "{{ etcd_cluster_name }}"
      data:
        "server.key": "{{ etcd_server_key_value }}"
        "server.crt": "{{ etcd_server_crt_value }}"
        "server-ca.crt": "{{ etcd_ca_crt_value }}"
