---
- name: Create '{{ cert_dir }}' tmp directory
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: 0700

- name: Generate CA Cert OpenSSL Config File
  template:
    src: ca_crt_conf.j2
    dest: "{{ ca_crt_conf_filename }}"

- name: Generate ETCD Peer Cert OpenSSL Config File
  template:
    src: etcd_peer_crt_conf.j2
    dest: "{{ etcd_peer_crt_conf_filename }}"

- name: Generate ETCD Client Cert OpenSSL Config File
  template:
    src: etcd_client_crt_conf.j2
    dest: "{{ etcd_client_crt_conf_filename }}"

- name: Generate ETCD Server Cert OpenSSL Config File
  template:
    src: etcd_server_crt_conf.j2
    dest: "{{ etcd_server_crt_conf_filename }}"

- name: Create ETCD CA Cert
  shell: "openssl req -nodes -x509 -newkey rsa:{{ rsa_key_size }} -keyout {{ etcd_ca_key_filename }} -out {{ etcd_ca_crt_filename }} -days {{ default_days }} -extensions v3_req -config {{ ca_crt_conf_filename }}"

- name: Create ETCD Peer Cert
  shell: |
    openssl genrsa -out {{ etcd_peer_key_filename }} {{ rsa_key_size }}
    openssl req -new -key {{ etcd_peer_key_filename }} -out {{ etcd_peer_csr_filename }} -config {{ etcd_peer_crt_conf_filename }}
    openssl x509 -req -sha256 -in {{ etcd_peer_csr_filename }} -CA {{ etcd_ca_crt_filename }} -CAkey {{ etcd_ca_key_filename }} -CAcreateserial -out {{ etcd_peer_crt_filename }} -days {{ default_days }} -extensions v3_req -extfile {{ etcd_peer_crt_conf_filename }}

- name: Create ETCD Client Cert
  shell: |
    openssl genrsa -out {{ etcd_client_key_filename }} {{ rsa_key_size }}
    openssl req -new -key {{ etcd_client_key_filename }} -out {{ etcd_client_csr_filename }} -config {{ etcd_client_crt_conf_filename }}
    openssl x509 -req -sha256 -in {{ etcd_client_csr_filename }} -CA {{ etcd_ca_crt_filename }} -CAkey {{ etcd_ca_key_filename }} -CAcreateserial -out {{ etcd_client_crt_filename }} -days {{ default_days }} -extensions v3_req -extfile {{ etcd_client_crt_conf_filename }}

- name: Create ETCD Server Cert
  shell: |
    openssl genrsa -out {{ etcd_server_key_filename }} {{ rsa_key_size }}
    openssl req -new -key {{ etcd_server_key_filename }} -out {{ etcd_server_csr_filename }} -config {{ etcd_server_crt_conf_filename }}
    openssl x509 -req -sha256 -in {{ etcd_server_csr_filename }} -CA {{ etcd_ca_crt_filename }} -CAkey {{ etcd_ca_key_filename }} -CAcreateserial -out {{ etcd_server_crt_filename }} -days {{ default_days }} -extensions v3_req -extfile {{ etcd_server_crt_conf_filename }}
