---
- name: Check if cert temp dir '{{ cert_dir }}' exists
  stat:
    path: "{{ cert_dir }}"
  register: stat_result

- name: Generate TLS Certs
  include: create_certs.yaml
  when: stat_result.stat.exists == False

- name: Create Secrets for Certs
  include: create_secrets.yaml
