---
- name: Create Etcd Peer TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_peer_secret_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "peer.key": "{{ etcd_peer_key_value }}"
        "peer.crt": "{{ etcd_peer_crt_value }}"
        "peer-ca.crt": "{{ etcd_ca_crt_value }}"

- name: Create Etcd Client TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_client_secret_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "etcd-client.key": "{{ etcd_client_key_value }}"
        "etcd-client.crt": "{{ etcd_client_crt_value }}"
        "etcd-client-ca.crt": "{{ etcd_ca_crt_value }}"

- name: Create Etcd Server TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ etcd_server_secret_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "server.key": "{{ etcd_server_key_value }}"
        "server.crt": "{{ etcd_server_crt_value }}"
        "server-ca.crt": "{{ etcd_ca_crt_value }}"

- name: Create Vault Client TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ vault_client_secret_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "vault-client-ca.crt": "{{ vault_ca_crt_value }}"

- name: Create Vault Server TLS Secret
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ vault_server_secret_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      data:
        "server.key": "{{ vault_server_key_value }}"
        "server.crt": "{{ vault_server_crt_value }}"
        "server-ca.crt": "{{ vault_ca_crt_value }}"
