---
- name: Create ETCD Cluster
  k8s:
    state: "{{ state }}"
    definition:
      apiVersion: "{{ etcd_api_version }}"
      kind: EtcdCluster
      metadata:
        name: "{{ etcd_cluster_name }}"
        namespace: "{{ namespace }}"
        labels:
          app: "{{ vault_app_name }}"
          vault_cluster: "{{ vault_cluster_name }}"
      spec:
        size: "{{ etcd_cluster_size }}"
        TLS:
          static:
            member:
              peerSecret: "{{ etcd_peer_secret_name }}"
              serverSecret: "{{ etcd_server_secret_name }}"
            operatorSecret: "{{ etcd_client_secret_name }}"
        pod:
          etcdEnv:
            - name: "ETCD_AUTO_COMPACTION_RETENTION"
              value: "1"
        repository: "{{ etcd_repository }}"
