apiVersion: v1
kind: Service
metadata:
  name: {{ include "memcached.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "memcached.name" . }}
    helm.sh/chart: {{ include "memcached.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
  selector:
    app.kubernetes.io/name: {{ include "memcached.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
